spring:
  application:
    name: recommendation-service
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null
  h2:
    console:
      enabled: true

promotion: action
server:
  port: 8083

#promotion:
#  sleep:
#    milliseconds: 10000
