server:
  port: 8083

spring:
  application:
    name: recommendation-service
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

api:
  connect:
    path: /
  bff:
    path: /
  services:
    account-service: http://localhost:8081
    contents-service: http://localhost:8082
    recommendation-service: http://localhost:8083