spring:
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null

api:
  services:
    contents-service: http://contents-service:8080